#  *-* Register *-* 
POST  http://localhost:5000/api/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@fakemail.com",  
    "password": "fakePass123",  
    "biz": true  
}

###

#  *-* Log in *-* 

POST  https://reactbizcardserverside.onrender.com/
Content-Type: application/json

{
    "email": "johndoe@fakemail.com",
    "password": "fakePass123"  
}

###
GET  http://localhost:5000/api/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzEwMjJlY2E5Mzc1MGM5ZjM4NGM2ZWIiLCJiaXoiOnRydWUsImlhdCI6MTY2MjAwMTkwMX0.p08Zp-0leM-drSfgFXTASsJAwdZe_joGwoG9p8niYhI

###

#  *-* addBizCard *-* 
POST    http://localhost:5000/api/addBizCard
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2Q3ZTY1MmIwY2UxNTk3N2JkMGUyZDciLCJiaXoiOnRydWUsImlhdCI6MTY3NTA5MzU4Nn0.cltplQqo4CCEmJxwXYgADnM_NE6b9e2OcF6whvo-Nqg


   {
   "title": "Bright Smile Dental",
    "subTitle": "Family and Cosmetic Dentistry",
    "description": "Bright Smile Dental provides comprehensive dental care for the whole family. Our experienced dentists offer a range of services, including cosmetic dentistry, to help you achieve a brighter, healthier smile.",
    "address": {
      "state": "California",
      "city": "San Francisco",
      "street": "Market Street",
      "houseNumber": "456",
      "zip": "94102"
    },
    "image": {
      "url": "https://brightsmiledental.com/img/logo.png",
      "alt": "Bright Smile Dental logo"
    },
    "bizNumber": "987654321",
    "phone": "+1-555-555-5556",
    "likes": ["f","f","f","f","f"],
    "web": "https://brightsmiledental.com",
    "email": "info@brightsmiledental.com",
    "createdAt": "2023-01-30T12:00:00Z"
}

###

#  *-* getBizCard *-* 
GET     http://localhost:5000/api/getBizCard/6310daebc3d516026c4e5a37
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzBmYjQ5MWJjZjc3ZjczOGQ3MjQwYzUiLCJiaXoiOnRydWUsImlhdCI6MTY2MTk3MzY0OX0.-IXDP97G24K-Gs-87MJJkOIkz-S7FdhiYhiMt4e8xfc

###

#  *-* updateBizCard *-* 
PUT   http://localhost:5000/api/updateBizCard/6310daebc3d516026c4e5a38
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzBmYjQ5MWJjZjc3ZjczOGQ3MjQwYzUiLCJiaXoiOnRydWUsImlhdCI6MTY2MTk3MzY0OX0.-IXDP97G24K-Gs-87MJJkOIkz-S7FdhiYhiMt4e8xfc

{
    "keyToUpdate": "tel",
    "value": "0542322223"
}

###

#  *-* deleteBizCard *-* 
DELETE    http://localhost:5000/api/deleteBizCard/6310daebc3d516026c4e5a37
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzBmYjQ5MWJjZjc3ZjczOGQ3MjQwYzUiLCJiaXoiOnRydWUsImlhdCI6MTY2MTk3MzY0OX0.-IXDP97G24K-Gs-87MJJkOIkz-S7FdhiYhiMt4e8xfc


###

#  *-* getUserBizCard *-* 
GET    http://localhost:5000/api/getUserBizCard/630fb491bcf77f738d7240c5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzBmYjQ5MWJjZjc3ZjczOGQ3MjQwYzUiLCJiaXoiOnRydWUsImlhdCI6MTY2MTk3MzY0OX0.-IXDP97G24K-Gs-87MJJkOIkz-S7FdhiYhiMt4e8xfc


###

#  *-* getAllCards *-* 
GET    http://localhost:5000/api/getAllCards/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzBmMzExZGU0ZTVmZmFjYjdkM2RlNzYiLCJiaXoiOnRydWUsImlhdCI6MTY2MTk0MDA0M30.I2zvWoe-YzwfKIh2GLXcEFKbvKaY9T7oxQwob4_bLaU
###