#  *-* Log in *-* 
POST  http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "johnDoe111"  
}

###
# Omer Goder
GET   http://localhost:5000/api/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzA4Yjc5Yjk4YjI0ODYwMjNlNmM2MjkiLCJiaXoiOmZhbHNlLCJpYXQiOjE2NjE1Nzk2MDF9.jUbMiU-XUxKtNim46MtpAbMNsEp_aR45rSMsbfNxoJQ
###
# Ori Guy
GET   http://localhost:5000/api/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzA4OGZlNzRjYTRhNTdlMDVhZWQ2MjMiLCJiaXoiOmZhbHNlLCJpYXQiOjE2NjE1ODcyNjh9.R9Wx0xFwiH3RK2afITIDT2G1uxEiBCNksj581081DqI
###
# Lee Malka
GET   http://localhost:5000/api/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzBhMzc4MDVlNzk2NTMzZjBhYjNlOTQiLCJiaXoiOnRydWUsImlhdCI6MTY2MTYxMzk1Mn0.HiY23Jo9z_nMpKGpX_f-m9Q9qhhIA4WLjeqEax94NEg
###
#John Doe
GET   http://localhost:5000/api/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzBkMDgxOWFiODNjYzlhOThkODEwYzkiLCJiaXoiOnRydWUsImlhdCI6MTY2MTc5ODQyNX0.k9TDUb9_x_qfJeJRGnZMEajxTMbCjueIdcljNWC1Pa4
###
# Avivit Guy
GET   http://localhost:5000/api/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzBkMTZlOGJkMmNlODQ1NzFmZjQzYzUiLCJiaXoiOnRydWUsImlhdCI6MTY2MTgwMjIxNn0.cbTuMiGMKEvePDB4LBu4_eEj9OJOyqlNVijgCCL3nus
###
GET   http://localhost:5000/api/login
###

#  *-* Register *-* 
POST  http://localhost:5000/api/register
Content-Type: application/json

{
    "name": "Ori Guy",
    "email": "origuydev@gmail.com",  
    "password": "123456789",  
    "biz": false  
}

###

#  *-* addBizCard *-* 
POST    http://localhost:5000/api/addBizCard
Content-Type: application/json
Authorization: Bearer JWT Token

{
    "bizName": "fiction business name",
    "description": "the most amazing fiction business",
    "address": "somewhere in Israel",
    "tel": "0541234567",
    "img": "The logo.jpg"
 
}
###
POST    http://localhost:5000/api/addBizCard
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzA4Yjc5Yjk4YjI0ODYwMjNlNmM2MjkiLCJiaXoiOmZhbHNlLCJpYXQiOjE2NjE1Nzk2MDF9.jUbMiU-XUxKtNim46MtpAbMNsEp_aR45rSMsbfNxoJQ

{
    "bizName": "Omer Engeneering",
    "description": "Engeneering services",
    "address": "Kiryat Ata, Israel",
    "tel": "0543589655",
    "img": "https://github.com/origuy/holocaust/blob/main/assets/Logo%20Text.png?raw=true"
 
}

###

#  *-* getBizCard *-* 
GET     http://localhost:5000/api/getBizCard/:630a385a5e796533f0ab3e9a
Authorization: Bearer JWT Token

###
GET     http://localhost:5000/api/getBizCard/630a385a5e796533f0ab3e9a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzA4OGZlNzRjYTRhNTdlMDVhZWQ2MjMiLCJiaXoiOmZhbHNlLCJpYXQiOjE2NjE1ODcyNjh9.R9Wx0xFwiH3RK2afITIDT2G1uxEiBCNksj581081DqI
###
GET     http://localhost:5000/api/getBizCard/630a385a5e796533f0ab3e9a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzBhMzc4MDVlNzk2NTMzZjBhYjNlOTQiLCJiaXoiOnRydWUsImlhdCI6MTY2MTYxMzk1Mn0.HiY23Jo9z_nMpKGpX_f-m9Q9qhhIA4WLjeqEax94NEg
###

#  *-* updateBizCard *-* 
PUT   http://localhost:5000/api/updateBizCard/630ae0bfd4ed7868d2f6751e
Content-Type: application/json
Authorization: Bearer JWT Token

{
    "keyToUpdate": "tel",
    "value": "0541234566"
}

###

#  *-* deleteBizCard *-* 
DELETE    http://localhost:5000/api/deleteBizCard/630d148735f77298d5268719
Authorization: Bearer JWT Token

###
#  *-* getUserBizCard *-* 
GET    http://localhost:5000/api/getUserBizCard/630a37805e796533f0ab3e94
Authorization: Bearer JWT Token

###
#  *-* getAllCards *-* 
GET    http://localhost:5000/api/getAllCards/
Authorization: Bearer JWT Token

###



