#  *-* Register *-* 
POST  http://localhost:5000/api/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@fakemail.com",  
    "password": "fakePass123",  
    "biz": true  
}

###

#  *-* Log in *-* 

POST  http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "johndoe@fakemail.com",
    "password": "fakePass123"  
}

###
GET  http://localhost:5000/api/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzEwMjJlY2E5Mzc1MGM5ZjM4NGM2ZWIiLCJiaXoiOnRydWUsImlhdCI6MTY3MjU5MzI5OH0.dMZ2T4r4ojl_itxHh1RYV0TBjqlTjCghz79bu-634nA

###

#  *-* addBizCard *-* 
POST    http://localhost:5000/api/addBizCard
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzEwMjJlY2E5Mzc1MGM5ZjM4NGM2ZWIiLCJiaXoiOnRydWUsImlhdCI6MTY3MjU5MzI5OH0.dMZ2T4r4ojl_itxHh1RYV0TBjqlTjCghz79bu-634nA

{
    "bizName": "John Web",
    "description": "The internet is a great place to find and share information, but it's not always the best place to for your company's digital communications and marketing campaigns. We here to make sure your digital footprint is the best 💖",
    "address": "Beer Sheva, Israel",
    "tel": "0541111111",
    "img": "https://images.pexels.com/photos/617278/pexels-photo-617278.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}
###

#  *-* getBizCard *-* 
GET     http://localhost:5000/api/getBizCard/6310daebc3d516026c4e5a37
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzEwMjJlY2E5Mzc1MGM5ZjM4NGM2ZWIiLCJiaXoiOnRydWUsImlhdCI6MTY3MjU5MzI5OH0.dMZ2T4r4ojl_itxHh1RYV0TBjqlTjCghz79bu-634nA

###

#  *-* updateBizCard *-* 
PUT   http://localhost:5000/api/updateBizCard/6310daebc3d516026c4e5a38
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzEwMjJlY2E5Mzc1MGM5ZjM4NGM2ZWIiLCJiaXoiOnRydWUsImlhdCI6MTY3MjU5MzI5OH0.dMZ2T4r4ojl_itxHh1RYV0TBjqlTjCghz79bu-634nA

{
    "keyToUpdate": "tel",
    "value": "0542322223"
}

###

#  *-* deleteBizCard *-* 
DELETE    http://localhost:5000/api/deleteBizCard/6310daebc3d516026c4e5a37
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzEwMjJlY2E5Mzc1MGM5ZjM4NGM2ZWIiLCJiaXoiOnRydWUsImlhdCI6MTY3MjU5MzI5OH0.dMZ2T4r4ojl_itxHh1RYV0TBjqlTjCghz79bu-634nA


###

#  *-* getUserBizCard *-* 
GET    http://localhost:5000/api/getUserBizCard/630fb491bcf77f738d7240c5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzEwMjJlY2E5Mzc1MGM5ZjM4NGM2ZWIiLCJiaXoiOnRydWUsImlhdCI6MTY3MjU5MzI5OH0.dMZ2T4r4ojl_itxHh1RYV0TBjqlTjCghz79bu-634nA


###

#  *-* getAllCards *-* 
GET    http://localhost:5000/api/getAllCards/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzEwMjJlY2E5Mzc1MGM5ZjM4NGM2ZWIiLCJiaXoiOnRydWUsImlhdCI6MTY3MjU5MzI5OH0.dMZ2T4r4ojl_itxHh1RYV0TBjqlTjCghz79bu-634nA
###